### ISSUE TITLE
Make event Open / Closed slider more specific

### ISSUE THREAD

**Issue by kevinrabinovich** [StudentRND/Clear#10]
The Open / Closed slider labeled ```EVENT``` currently has a pretty drastic effect when toggled—cancelling the event and emailing all attendees. This could be misinterpreted as allowing or disallowing registrations. Change the language on the current slider to reflect that toggling it has drastic changes. Also, add another slider for closing / opening regsitrations.

**Comment by tylermenezes** [comment]
That's incorrect, the EVENT slider is tied to a setting called allow_registrations. It doesn't cancel the event, and has exactly the effect you described as ideal.
