### ISSUE TITLE
Login: Goes to "Something went wrong page"

### ISSUE THREAD

**Issue by Jaberer** [StudentRND/Clear#17]
I believe it happens when I type in a special character in the UserName?
Something with the input validation perhaps?

ie: 
Username: josephzhong@studentrnd.org (that's not actually my username)
pass: asdfasdfasdf

[Goes to....](https://www.dropbox.com/s/1iqoghwfev26tmt/Screenshot%202015-08-19%2001.09.56.png?dl=0)

Doesn't happen with 
josephzhong
asdfasdfasdf

Without the `@` I simply get the little message of an incorrect username/pass

**Comment by tjhorner** [comment]
It's internally a 404.

**Comment by Jaberer** [comment]
:+1:


Joseph Zhong





On Mon, Sep 7, 2015 at 3:16 PM -0700, "TJ Horner" <notifications@github.com> wrote:
It's internally a 404.

---
